[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
healthcheckUrl = "/home"

[[env]]
name = "production"
variables = { FLASK_ENV = "production", PYTHONUNBUFFERED = "1" }
